### ISSUE TITLE
ignore `node_modules/` in default config

### ISSUE THREAD

**Issue by petschki** [plone/meta#111]
Just re-configed `plonetheme.barceloneta` and it would be great if `node_modules` would be ignored too per default.

**Comment by gforcada** [comment]
I see that `plone/meta` removed:

```
bower_components
node_modules
.cache
.DS_Store
.idea
plonetheme/barceloneta/static/vendor/
plonetheme/barceloneta/static/barceloneta.css.map
.vscode
```

The `plonetheme` paths do not make sense to keep it in `plone/meta`, but what about the others? Should we add any?

I'm happy to review any PR for [`gitignore`](https://github.com/plone/meta/blob/master/config/default/gitignore.j2) 😄
