### ISSUE TITLE
Use z3c.dependencychecker to analyze package dependencies

### ISSUE THREAD

**Issue by gforcada** [plone/meta#12]
This way we can better understand what are the actual dependencies between packages.

**Comment by gforcada** [comment]
I almost got it with https://github.com/reinout/z3c.dependencychecker/pull/99 but another PR is needed https://github.com/reinout/z3c.dependencychecker/pull/101

At least with this last PR `plone.batching` validates, once dependencies are adjusted 🤞🏾 🍀

**Comment by mauritsvanrees** [comment]
I would be happy to see dependencychecker in here. That will help untangling dependencies in Plone.

But I am not sure if it is good to make this a requirement that should pass with `tox -e lint`. At least I would be wary of dropping unneeded dependencies within a Plone 6.0.x bugfix release.

Ah, but it seems that dependencychecker does not give an exit code higher than zero when run, unless there is some syntax error or similar.

Introducing a non-zero exit code could be nice for later. Maybe with an extra option like `--allow-unneeded-requirements` so it does not fail when unneeded requirements are there, but only when there are missing dependencies.
Just brainstorming here. :-)

**Comment by mauritsvanrees** [comment]
BTW, thanks for your work on dependencychecker! It is much closer now to being usable for real in Plone.

**Comment by gforcada** [comment]
> BTW, thanks for your work on dependencychecker! It is much closer now to being usable for real in Plone.

Welcome! we use it internally at work, so whenever a dependency is added/removed we get alerted on them.

I don't think it is much of a problem to remove unneeded dependencies, I would say that it is 99% likely that if you drop, say `Products.CMFCore` from `plone.batching` because it is not used, your pipeline will not fail because `Products.CMFCore` is being used by hundred other packages, or? 🤔 

We can introduce a third tox environment(? I guess from `-e`) to run the dependency checkers and ensure that it never fails, just reports, this way we can see how that is.

Though, we can [see that already on jenkins.plone.org](https://jenkins.plone.org/view/Dependencies/job/qa-undeclared-dependencies/lastSuccessfulBuild/artifact/deps.txt/*view*/) 😅 

It would be nice to record the length of this report over time, to see if we are actually fixing the problem or not 😆 

I hope that https://github.com/reinout/z3c.dependencychecker/pull/101 can get merged before Alpine City Sprint so we can start using it there 🤖 🚀
