### ISSUE TITLE
Detect and configure pytest or zope.testrunner

### ISSUE THREAD

**Issue by gforcada** [plone/meta#120]
See https://github.com/plone/plone.distribution/pull/26

It is a _bit_ broken, given that `plone.distribution` is running its tests with `pytest` but on `tox.ini` for both `test` and `coverage` we use `zope.testrunner` 😕 

Plone core might not move _fast_ to `pytest` (if ever 🤔 ) but specially for add-ons, and all the work that @ericof is making to lower the efforts to create add-ons, I see that in the future lots of packages will start using `pytest`.

If we want (me! 🤚🏾 ) that `plone/meta` __is__ the way to configure plone core and add-ons, we will have to configure one or the other test runner.

**Comment by ericof** [comment]
@gforcada Do you have any ideas on how we could achieve this?

**Comment by gforcada** [comment]
Seems you already found the way, great job! 🎉
