### ISSUE TITLE
Rename main branch from master to main

### ISSUE THREAD

**Issue by ericof** [plone/meta#125]

**Comment by gforcada** [comment]
For this repository or rather for _all_ plone repositories? 🤔 😅 

We have references to the `master` branch name in `meta.yml.j2`: https://github.com/plone/meta/blob/master/config/default/meta.yml.j2

We should start creating tags I guess, so we can avoid that.

The other thing is the shared organization wide workflow, which is getting deprecated with this new wave of reconfiguration that I'm doing these days. It also has a reference to `master`.

So yes, let's plan that 👍🏾 

Another matter is _all repositories_: from the top of my head:

- mr.roboto and jenkins should be reviewed
- on `buildout.coredev` `sources.cfg` should be reviewed
- anything else? 🤔 

Here on `meta` there are a few scripts, copied from `zopefoundation/meta`, that with a bit of tweaking could be used to do the mass creation of the `main` branch and configuring it on GitHub to be the default, and protected, branch.

**Comment by ericof** [comment]
@gforcada, I'm talking about this one for now.
A few years ago, I had a script ready to do the master-> leading dance for all repositories, but we never prioritized that, so let's make sure the new ones are correct.

**Comment by gforcada** [comment]
The change is done, we have a `main` branch which is the default.

The GHA already point to the `main` branch, and a new wave of reconfiguration should happen, but that's not too much of a problem, as the GHA themselves are rather simple anyway 🍀
