### ISSUE TITLE
Integrate collective.recipe.vscode?

### ISSUE THREAD

**Issue by gforcada** [plone/meta#134]
I've seen it at least in a plone core package (`plone.portlet.collection`), but in general VSCode seems to be one of the preferred text editors as of late.

I use it every now and then, but this concept of language servers, and providing hints to the text editor to find code imports sounds interesting in general.

Is that something that could be configure/provided via `plone/meta` or I did not get what that's for? 🍀 😅

**Comment by jensens** [comment]
What does it do and why would one need such recipe in a buildout-less world?

**Comment by gforcada** [comment]
Indeed, seems it is not so much useful on a buildout-less environment, so probably not worth it.
