### ISSUE TITLE
Display the project dependencies in a graph

### ISSUE THREAD

**Issue by gforcada** [plone/meta#14]
That together with #12 will help us spot where `six` is still being used, or how many packages have dependencies with `plone.app.portlets` etc and where do we have to cut the dependencies from ✨ 

While doing extensive research on this I came across [`pipdeptree`](https://github.com/tox-dev/pipdeptree) which works out of what's installed on a given virtualenv. So if we use it on a `buildout.coredev` checkout with lots of packages in their edit mode, we can slowly but surely keep reducing the amount of dependencies and double loopings and what not that we have accumulated over the years.

There is also [`pydeps`](https://pypi.org/project/pydeps/) that might be worth having a look, though this one is mostly to see where the modules from a distribution depend on each other (internal circular dependencies anyone?! 🥳 ), but its graphs are quite nice and for visual persons that might help 😄 

Both `pipdeptree` and `pydeps` can generate dot/svg and other graph formats, which is great for later exploration and fine tuning (like removing setuptools from all and every leaf in `pipdeptree` output for example 🍀 ).

**Comment by gforcada** [comment]
With `actions/upload-artifact` we can store `pipdeptree` output on GitHub, so it can be inspected later.

Something like that:

```yml
# check project dependencies
- name: QA
  run: tox -e dependencies

- uses: actions/upload-artifact@v3
  with:
    name: dependencies-graph
    path: dependencies.svg
```

@mauritsvanrees should we add a switch to enable it conditionally? 🤔 so that it is an opt-in action that we can decide on a per-project basis? For `Products.CMFPlone` or `Products.CMFCore` might not make much sense, way too many dependencies, but for non `plone.app` packages, might be more useful to keep an eye on them to ensure they don't grow more dependencies 😄 🍀

**Comment by davisagli** [comment]
@gforcada Is it possible to embed an svg as a data URL in Markdown? If so then it might be possible to do this instead of uploading an artifact, which would make it possible to view the output on the Summary tab of the action without needing to download the file. https://github.blog/2022-05-09-supercharging-github-actions-with-job-summaries/

**Comment by gforcada** [comment]
Oh, good idea, though, depending on the distribution, it's rather huge, so you will want to download it anyway.

The graph that [`pydeps`](https://pypi.org/project/pydeps/) generates, which are the internal structure of the distribution, that might make more sense to embed, as that will be smaller (again depending on the distribution).
