### ISSUE TITLE
Another linter: pylint

### ISSUE THREAD

**Issue by gforcada** [plone/meta#18]
Though this one, does report __a lot__ of things 😅 but a subset of it might be interesting, we can use one or two projects to see if it does really make sense. 🍀

**Comment by mauritsvanrees** [comment]
I am inclined to use either `flake8` or `pylint`, and not both. I am only used to flake8 though, so may need more experience with pylint.

**Comment by gforcada** [comment]
Same happens with me, I have made several plugins for `flake8` as well, this issue was more of an open question as to whether we want to use it, as `pylint` has much more advanced checks, that might be way too much... ⚖️ 😅

**Comment by gforcada** [comment]
I was testing it with my loved [guinea pig](https://github.com/plone/plone.batching) 😅 and it feels that there is potential to improve the code with its suggestions, but there are way too many checks that we should ignore 😕 

Probably we can revisit that at a later point IMHO
