### ISSUE TITLE
Syntax Error in test.yml

### ISSUE THREAD

**Issue by 1letter** [plone/meta#190]
I testing in a dummy addon the plone/meta integration. every run of the meta.yml action fails, even though the single jobs are green. Example:
https://github.com/1letter/my.addon/actions/runs/6842732409

every run of the action provided by plone/meta throw me an error releated to https://github.com/plone/meta/blob/main/.github/workflows/test.yml?

**Update:**

ah i see, that a configuration of a global variable is needed. i do this in my dummy package. Now another error occur.

TEST_PYTHON_VERSIONS
3.8,3.9,3.10,3.11

@gforcada What ist the right Syntax for the Definition?

**Update**
Thats what i'm missing, now ist all fine:

TEST_OS_VERSIONS
["ubuntu-22.04", "ubuntu-20.04"]

TEST_PYTHON_VERSIONS
["3.8","3.9","3.10","3.11"]

**Comment by gforcada** [comment]
Oh, I see, let's reopen that and provide a fallback to those values if they are not there, otherwise everyone will get the same problem as you are having 😕

**Comment by gforcada** [comment]
Seems that the [`fromJSON`](https://docs.github.com/en/actions/learn-github-actions/expressions#fromjson) function we are using with those variables can not have a fallback value 😕 

We can at least document it on the README files and at some point stop using them, but use some local variable, so the GHA YAML file is self-contained? 🤔

**Comment by gforcada** [comment]
For now, at least some documentation is written: https://github.com/plone/meta/commit/6a477508c170befe8069a659f7ed3845036a4161
