### ISSUE TITLE
Decide on standard towncrier snippets.

### ISSUE THREAD

**Issue by mauritsvanrees** [plone/meta#2]
Breaking, feature and bugfix are obvious.

`plone.restapi` has these extra:

```
[[tool.towncrier.type]]
directory = "documentation"
name = "Documentation"
showcontent = true

[[tool.towncrier.type]]
directory = "internal"
name = "Internal"
showcontent = true
```

Without these, they will usually end up under bug fixes.

We could consider an extra one for tests, as we sometimes have fixes that are only in tests. But could be filed under 'internal' as well:

```
[[tool.towncrier.type]]
directory = "tests"
name = "Tests"
showcontent = true
```

If we do not add these, the danger is that someone is used to having `.documentation` in here for other packages, adds a news snippet, and then the snippet is totally ignored by towncrier. Or gives an error during release, forcing the releaser to solve it at that point.

**Comment by gforcada** [comment]
Internal, docs and tests sound good, we will have to do some community postings to let everyone know about them though, otherwise, as you say, `bugfix` will be overused for them.
