### ISSUE TITLE
`main` branch isn't protected

### ISSUE THREAD

**Issue by stevepiercy** [plone/meta#224]
This could be a nasty security problem.

![Screenshot 2024-05-05 at 1 32 31 PM](https://github.com/plone/meta/assets/102112/bdb57753-6047-42a6-9f26-e2eaab5cc260)

**Comment by davisagli** [comment]
@stevepiercy Thanks, I added a branch protection rule to require review before merging a PR.

Reminder: If you find a potential security issue, please report it privately rather than in a public issue.

**Comment by stevepiercy** [comment]
It was already publicly disclosed on the repo's home page by GitHub.
