### ISSUE TITLE
Include`pytest-plone` mapping to 

### ISSUE THREAD

**Issue by ericof** [plone/meta#232]
Add the following mapping to the `[tool.dependencychecker]` section in pyproject.toml if the user selects pytest

```toml
pytest-plone = ['pytest', 'zope.pytestlayer', 'plone.testing', 'plone.app.testing']
```

**Comment by gforcada** [comment]
Seems nobody worked on it 🫣 

Do we want that to be conditional (optimal), or can we just go with it? That makes it so much easier, as it is adding a single line on `pyproject.toml` and that would be it ✨
