### ISSUE TITLE
Another linter: pyroma

### ISSUE THREAD

**Issue by mauritsvanrees** [plone/meta#28]
This checks the `setup.py` and/or `setup.cfg`.
Most Plone packages are in good shape. The complaint I see the most now from pyroma is about python_requires not being set. Sample run in `plone.schemaeditor`, requiring a 10 out of 10:

```
$ pyroma -n 10 .
------------------------------
Checking .
Getting metadata for wheel...
Found plone.schemaeditor
------------------------------
You should specify what Python versions you support with the 'requires-python'/'python_requires' metadata.
------------------------------
Final rating: 8/10
Philadelphia
------------------------------
```

And in CMFPlone:

```
$ pyroma -n 10 .
------------------------------
Checking .
Getting metadata for wheel...
Found Products.CMFPlone
------------------------------
Final rating: 10/10
Your cheese is so fresh most people think it's a cream: Mascarpone
------------------------------
```

**Comment by mogiiee** [comment]
Hey @mauritsvanrees  I am a student and want to contribute to Plone... could you suggest a project or a repository which would help me get started?

**Comment by gforcada** [comment]
@mogiiee if you want to contribute to plone, it might be much better to ask on community.plone.org 😉 there is also a [plone discord chat](https://discord.gg/zFY3EBbjaj) as well 😄
