### ISSUE TITLE
Do not push by default

### ISSUE THREAD

**Issue by mauritsvanrees** [plone/meta#3]
The Zope version pushes the resulting branch by default. You can switch this off with `--no-push`.
I myself prefer to have a look before pushing, especially when problems are reported and I think: I will continue for now and have a look once the script is finished doing its work.

So I would like to not push, and then probably have a `--push` option to switch this on again. Or don't bother with such an option: typing `git push` yourself at the end is not so hard.

**Comment by gforcada** [comment]
I guess, their idea was the same at the beginning, and once most of the repos are already configured and they are mostly in maintenance mode/applying a few fixes here and there, they are confident enough to have the _push_ as the default strategy.

Hopefully we get there soon 🚀 but it does make sense indeed 😄

**Comment by mauritsvanrees** [comment]
@petschki We probably *do* want to restrict access a bit to this central repo.  I see that currently only Owners of the plone organization have full access, others only Read access.  There is an ongoing process of being stricter in who can do what, and who ends up in which GitHub team.  Especially new contributors should not immediately be able to change all kinds of things here.

Of course we trust you and you are very welcome to make branches.  For now I have given you write access to the `plone/meta` repo.
This will probably change at some point into giving access to either an existing or a new team.

cc @fredvd

**Comment by mauritsvanrees** [comment]
I have also given the CI team admin access to this repo.
