### ISSUE TITLE
First run format, then lint

### ISSUE THREAD

**Issue by mauritsvanrees** [plone/meta#4]
When configuring a package, the code runs `tox -p auto`, which is what Zope does too. Currently for our setup this means `format` and `lint`. This is confusing, because `lint` will complain about code that is being changed in parallel by `format`. For example see this output:

```
$ bin/python config-package.py --no-push ../../6.0/src/plone.batching
plone.batching is already configured for this config type, updating.
format: FAIL ✖ in 0.24 seconds
format: commands[0]> sh -c 'find plone -name "*.py" | xargs pyupgrade --py38-plus *.py'
format: exit 1 (0.16 seconds) /Users/maurits/community/plone-coredev/6.0/src/plone.batching> sh -c 'find plone -name "*.py" | xargs pyupgrade --py38-plus *.py' pid=46845
lint: commands[0]> sh -c 'find plone -name "*.py" | xargs flake8 *.py'
conf.py:13:1: F401 'sys' imported but unused
...
plone/batching/batch.py:276:44: E127 continuation line over-indented for visual indent
plone/batching/batch.py:286:1: E305 expected 2 blank lines after class or function definition, found 1
plone/batching/browser.py:63:1: E303 too many blank lines (3)
lint: exit 1 (0.62 seconds) /Users/maurits/community/plone-coredev/6.0/src/plone.batching> sh -c 'find plone -name "*.py" | xargs flake8 *.py' pid=46846
  format: FAIL code 1 (0.24=setup[0.08]+cmd[0.16] seconds)
  lint: FAIL code 1 (0.69=setup[0.07]+cmd[0.62] seconds)
  evaluation failed :( (0.77 seconds)
Rewriting conf.py
Rewriting setup.py
Rewriting plone/__init__.py
Rewriting plone/batching/interfaces.py
Rewriting plone/batching/batch.py
Rewriting plone/batching/__init__.py
Rewriting plone/batching/browser.py
Rewriting plone/batching/utils.py
Rewriting plone/batching/tests.py
ABORTING: Please fix the errors shown above.
Proceed anyway (y/N)?
```

When I then continue anyway, and run lint by hand, it no longer complains. Okay, wait, it still complains about a few things that need manual fixing. But the point is valid: first run `format`, then `lint`, either separately or in one command:

```
tox -e format,lint
```

**Comment by gforcada** [comment]
Good point, not sure if we can tell the order that `auto` takes somehow 🤔 otherwise it would mean that if we have to specify it on `config-package.py` for every new `tox` target we will have to update it 😕

**Comment by gforcada** [comment]
As usual, RTFM and then you understand things 😅 `-p` means run all targets in _parallel_ 

We can change that to actually run `format` and then `lint`, until we start using `tox` also for testing in multiple python versions I think it should be fine, we will not add hundreds of targets 🍀
