### ISSUE TITLE
Integrate pipforester

### ISSUE THREAD

**Issue by gforcada** [plone/meta#42]
This would allow us to detect, and fix, cyclic dependencies, and ensure no new cyclic dependencies are added.

Thanks to @jensens, and contributors!, that they created it during the Alpine City Sprint 2023 🎉 

https://github.com/collective/pipforester

**Comment by gforcada** [comment]
@ale-rt currently, all our formatting and code analysis is done with `pre-commit`. Should we make `pipforester` another pre-commit tool? 🤔 that's, by all means IMHO, a tool that you don't want to run on every commit, but rather only on CI...

Is there a way to configure `pre-commit` checks that are _disabled_ by default? 🤔

**Comment by mauritsvanrees** [comment]
You could setup the hook to only run when `setup.py`, `setup.cfg` or `pyproject.toml` is edited.
But still, this then means that pre-commit would reinstall the package under development, with hundreds of dependencies, and this takes too long, even if all dependencies were already installed.

Also, it may be good to combine `pipforester` with `z3c.dependencychecker` and `pipdeptree` into one tox environment. Currently, if I check the disk usage of a package where I ran all tox environments, I already get this:

```
$ du -sh .tox/*
311M	.tox/dependencies
310M	.tox/dependencies-graph
 30M	.tox/format
 30M	.tox/lint
385M	.tox/test
```

This wastes disk usage and time.

**Comment by ale-rt** [comment]
> @ale-rt currently, all our formatting and code analysis is done with `pre-commit`. Should we make `pipforester` another pre-commit tool? thinking that's, by all means IMHO, a tool that you don't want to run on every commit, but rather only on CI...
> 
> Is there a way to configure `pre-commit` checks that are _disabled_ by default? thinking

**IF** you want to use pre-commit to run `pipforester` I would suggest you to provide a second config file and then run:

```shell
pre-commit run --config .ci-pre-commit.yaml --all
```

Certainly you do not want to run that hook for every commit...

**Comment by gforcada** [comment]
@ale-rt good point, it does _not_ have to be a `pre-commit` hook indeed, we have GitHub Actions as well 👍🏾 

@mauritsvanrees oh, indeed that's quite a lot of disk space, fortunately almost no one but a few of us will run these tox environments on more than a handful of repositories... but indeed merging a few of them might be worth it 👍🏾

**Comment by gforcada** [comment]
With #94 it will be integrated, but we already have #77 I'm closing this one.
