### ISSUE TITLE
doctests not found, or too much of them found, with pytest

### ISSUE THREAD

**Issue by gforcada** [plone/meta#46]
Our friendly guinea pig, aka [plone.batching](https://github.com/plone/plone.batching) has [one doctest](https://github.com/plone/plone.batching/blob/a83e171975edbf670cd5ae9b10b66dfa02d594ee/plone/batching/tests/test_batching.py) which is found and run by `zope.testrunner` but somehow 🤷🏾 not found, by default, by `pytest` +  `gocept.pytestlayer`.

Somehow despite the `doctest.DocFileSuite` call, it is still ignored by `pytest`, no idea why 👻 

`pytest` has a [`--doctest-glob`](https://docs.pytest.org/en/7.1.x/how-to/doctest.html) switch that if passed it tries to run both `batching.rst` but also [`docs/usage.rst`](https://github.com/plone/plone.batching/blob/a83e171975edbf670cd5ae9b10b66dfa02d594ee/docs/usage.rst) 😅 

Funnily enough, then `batching.rst`, the expected test to run, does run and it works, but `usage.rst` does not 🤦🏾 

One way out could be to convert `batching.rst` into a plain python test, or make the decision to keep all documentation in markdown (`.md`) and doctests in reStructuredText (`.rst`) as to avoid `pytest` to mix them.

Ideas? 🤔

**Comment by mauritsvanrees** [comment]
Turning the real docs into MarkDown would seem best to me.

**Comment by gforcada** [comment]
As `pytest` is a bit far from now, we probably don't need to care much about this now..
