### ISSUE TITLE
Configure codespell better

### ISSUE THREAD

**Issue by mauritsvanrees** [plone/meta#57]
This is a discrete issue based on a discreet discussion in a [plone.base PR](https://github.com/plone/plone.base/pull/28#discussion_r1127542912)
`codespell` has some false positives that it complains about.  I at least see it complaining in a few packages that "discreet" should be "discrete".  Both are correct.

1. Currently we add `discreet` to the codespell additional-ignores in .meta.toml, in discrete repos (can't resist and be discreet about this; oops I did it again).
2. We could make this standard and add this in additional-ignores in plone/meta.
3. This is in a discrete word list called "rare".  We can discreetly ignore this by using only the "clear" word list, and call `codespell --builtin clear`. In the pre-commit config file that is: `args: [--builtin, clear]`.
4. We can keep using the "rare" list, but use `codespell -I .codespell-custom-good-spellings.txt` and have `discreet` in there.  I think you can also add something like `ignore-words = '.codespell-custom-good-spellings.txt'` in `pyproject.toml`.  That is not really different from our current solution with additional-ignores though.

I am inclined to ignore the rare word list and only use the clear word list.  So option 3.  This is the easiest change, and makes it faster to configure a package with this, because there will be fewer exceptions.

**Comment by gforcada** [comment]
Sounds like a good idea (option `3`). We would still need to support a custom list of other words to ignore though.

In `plone.protect` for example we have `ignore-words-list = "discreet,fo,parms"`, so adding an option in `.meta.toml` to append `fo,parms` would be a good solution IMHO 👍🏾
