### ISSUE TITLE
Add .gitignore

### ISSUE THREAD

**Issue by mauritsvanrees** [plone/meta#62]
Not all packages need the same `.gitignore`, so I don't think we can keep a file here in meta and copy it over, and expect devs to edit `.meta.toml` when they want to add more lines.

Maybe we can have a list here in meta and when configuring a package we check if each item is there, and add the missing ones.

Example: I regularly add `.tox`.

Everyone has their own pet peeves.  Maybe take part of the list in [`bobtemplates.plone`](https://github.com/plone/bobtemplates.plone/blob/main/bobtemplates/plone/addon/.gitignore.bob)?

**Comment by davisagli** [comment]
> Everyone has their own pet peeves.

Individual pet peeves can be addressed by adding them to ~/.gitignore instead of to a specific repository.

But it's also a reasonable use case that repositories will vary in what they need to ignore at the scope of the repository.

**Comment by gforcada** [comment]
Having a basic template would be great yes, and with the lean approach on settings/configuration points, it would mean to have a single option on `.meta.toml` where to list the extra files that one wants to ignore in git ✨ 

Looks doable but not urgent to me 😄 PRs welcome 👍🏾
