### ISSUE TITLE
Ignore `zpretty` in some repositories

### ISSUE THREAD

**Issue by gforcada** [plone/meta#63]
Although `meta` is to standarize the configuration across repositories, now and then we have to tweak it, to bend to each repositories' needs.

Given that a few repositories had some `zpretty` problems, might it be a good idea, that on those repositories we remove the entry on `.pre-commit-config.yaml` so we can still benefit from `pre-commit` but not hindering the migration to the standard configuration?

**Comment by mauritsvanrees** [comment]
As temporary action, that can work yes.
But so far we have been able to figure out what was wrong, and have a quick fix in `zpretty` or mostly change the original template in a way that `zpretty` does not break it.

**Comment by gforcada** [comment]
Indeed, most of the times, it's you the one that finds the problem though, so I don't want to burden you with too much issues 😓
