### ISSUE TITLE
Allow OS packages to be installed to run tests on shared workflow

### ISSUE THREAD

**Issue by gforcada** [plone/meta#65]
See the GHA on [this PR](https://github.com/plone/Products.PortalTransforms/pull/55).

We need `wv` system dependency, but so far we don't do that on the [shared workflow](https://github.com/plone/meta/blob/master/shared-workflows/tests.yml).

We might have a specific tests for it, or allow to pass OS packages to be installed before running tests... 🤔

**Comment by mauritsvanrees** [comment]
Maybe set an environment variable `OS_DEPENDENCIES` in the GitHub package settings, and read it in the shared workflow?

**Comment by gforcada** [comment]
Indeed, as soon as there are almost all packages configured, then I will look at the few corner cases that need some extra configuration to keep them running.

We can then later experiment with adding more python versions support, or other OS versions, maybe run those as weekly jobs, so we at least ensure that the whole matrix of `OS x python version` run and work, etc 🌈 🦄
