### ISSUE TITLE
Archive more repositories?

### ISSUE THREAD

**Issue by gforcada** [plone/meta#74]
We have +350 repositories that are __not archived__.

~100 of them have not been touched since 2018. I think is rather safe to archive them.

Archiving means making them read-only, they still can be cloned, but no write operations (issues or PRs either? 🤔 ) would be allowed.

This would mean that we _only_ have to try to tame the other ~250 still left 😅 

This issue goes together with #73 

With both put in motion, it would give us much more focus on where to spend the time, but also specially, signal to external/potential contributors where to NOT spend time on 🍀

**Comment by gforcada** [comment]
We could update their `README` files just before archiving them by mentioning how to ask to get a repository active again.

How should that go? 🤔 

```text
This repository is archived, if you consider using it again,
please refer to XXX to get in unarchived.
```

Of course the `XXX` should be cleared up 😅 

IMHO we could point users to https://community.plone.org so we have a safe space to handle those requests. _Polluting_ even more CMFPlone seems like a not so much of a good idea to me.

This way, we point users to newer approaches (squid -> varnish recipes, as a simple example, or most of the js packages -> mockup) as a solution, rather un-archiving a repository. 🤔

**Comment by davisagli** [comment]
@gforcada Can you show a list of the repositories that would be archived? If I see the specific names it might remind me if some of them should still be active for some reason.

**Comment by stevepiercy** [comment]
I would suggest the following modification. I would assume the task would fall to the AI Team.

```markdown
This repository is archived and read only.
If you want to unarchive it, then post to the [Admin & Infrastructure (AI) Team category on the Plone Community Forum](https://community.plone.org/c/aiteam/55).
```

**Comment by gforcada** [comment]
Thanks @stevepiercy for the suggestion ✨

@davisagli a first quick list might be:

- [plone.app.securityalert](https://github.com/plone/plone.app.securityalert)
- [Products.FoundationMember](https://github.com/plone/Products.FoundationMember)
- [plone.transforms](https://github.com/plone/plone.transforms)
- [plone.phonehome](https://github.com/plone/plone.phonehome)
- [buildout.atlassian](https://github.com/plone/buildout.atlassian)
- [svn-migrate](https://github.com/plone/svn-migrate)
- [Products.CMFTestCase](https://github.com/plone/Products.CMFTestCase)
- [plone.recipe.squid](https://github.com/plone/plone.recipe.squid)
- [plone.app.jqueryui](https://github.com/plone/plone.app.jqueryui)
- [plone.app.texttile](https://github.com/plone/plone.app.texttile)
- [plone.app.imagetile](https://github.com/plone/plone.app.imagetile)
- [plone.contentbrowser](https://github.com/plone/plone.contentbrowser)
- [plone.app.contenttile](https://github.com/plone/plone.app.contenttile)
- [feeds.plone.org](https://github.com/plone/feeds.plone.org)
- [plone.relations](https://github.com/plone/plone.relations)
- [plone.app.mediarepository](https://github.com/plone/plone.app.mediarepository)
- [buster-selenium](https://github.com/plone/buster-selenium)
- [plone.app.layoutpage](https://github.com/plone/plone.app.layoutpage)
- [plonejenkins.middleware](https://github.com/plone/plonejenkins.middleware)
- [plone.github.com](https://github.com/plone/plone.github.com)
- [plone.app.s5slideshow](https://github.com/plone/plone.app.s5slideshow)
- [plone.app.jscalendar](https://github.com/plone/plone.app.jscalendar)
- [plone.app.sarissa](https://github.com/plone/plone.app.sarissa)
- [uitesting](https://github.com/plone/uitesting)
- [coredev.vagrant](https://github.com/plone/coredev.vagrant)
- [plone-org-haproxy](https://github.com/plone/plone-org-haproxy)
- [security-mockups](https://github.com/plone/security-mockups)
- [archetypes.kss](https://github.com/plone/archetypes.kss)
- [diazotheme.coolblue](https://github.com/plone/diazotheme.coolblue)
- [plone.app.hud](https://github.com/plone/plone.app.hud)
- [mockup-extra](https://github.com/plone/mockup-extra)
- [plone.recipe.zope2zeoserver](https://github.com/plone/plone.recipe.zope2zeoserver)
- [plone.directives.dexterity](https://github.com/plone/plone.directives.dexterity)
- [plone.app.page](https://github.com/plone/plone.app.page)
- [Dash-User-Contributions](https://github.com/plone/Dash-User-Contributions)
- [Installers-OS-X](https://github.com/plone/Installers-OS-X)
- [wicked](https://github.com/plone/wicked)
- [plone.multilingual](https://github.com/plone/plone.multilingual)
- [plone.vulnerabilitychecks.tests](https://github.com/plone/plone.vulnerabilitychecks.tests)

Those are the repositories that have not been modified for the longest.

One can go to the `Repositories` tab in [`plone`](https://github.com/plone) organization, filter by `archived:false` and go to the last pages 😄

**Comment by davisagli** [comment]
@gforcada +1, that list makes sense to archive

**Comment by gforcada** [comment]
@davisagli thanks! all of them archived 🧹 ✨ 

May I ask if you agree on the following batch?

- [performance-testing](https://github.com/plone/performance-testing)
- [Products.Relations](https://github.com/plone/Products.Relations)
- [plone.mockup](https://github.com/plone/plone.mockup)
- [plonetheme.ploneorg](https://github.com/plone/plonetheme.ploneorg)
- [plone.fieldsets](https://github.com/plone/plone.fieldsets)
- [plone.app.filewidgets](https://github.com/plone/plone.app.filewidgets)
- [jump.into](https://github.com/plone/jump.into)
- [plone.app.jquery](https://github.com/plone/plone.app.jquery)
- [mockup-core](https://github.com/plone/mockup-core)
- [plone.app.stagingbehavior](https://github.com/plone/plone.app.stagingbehavior)
- [Products.PloneOrg](https://github.com/plone/Products.PloneOrg)
- [buildout.deco](https://github.com/plone/buildout.deco)
- [plone.app.themeeditor](https://github.com/plone/plone.app.themeeditor)
- [Products.ATReferenceBrowserWidget](https://github.com/plone/Products.ATReferenceBrowserWidget)
- [plone.app.kss](https://github.com/plone/plone.app.kss)
- [ploneorg.admin](https://github.com/plone/ploneorg.admin)
- [plone.vulnerabilitychecks.instance_startup](https://github.com/plone/plone.vulnerabilitychecks.instance_startup)
- [plone.vulnerabilitychecks.buildout](https://github.com/plone/plone.vulnerabilitychecks.buildout)
- [plone.vulnerabilitychecks.core](https://github.com/plone/plone.vulnerabilitychecks.core)
- [plone.pluggableauth](https://github.com/plone/plone.pluggableauth)
- [communication.plone5-posters](https://github.com/plone/communication.plone5-posters)
- [txtfilter](https://github.com/plone/txtfilter)
- [plone.app.contentlistingtile](https://github.com/plone/plone.app.contentlistingtile)
- [plone.app.toolbar](https://github.com/plone/plone.app.toolbar)
- [plone-org-nginx](https://github.com/plone/plone-org-nginx)
- [plonetheme-preloader](https://github.com/plone/plonetheme-preloader)
- [plone.formwidget.captcha](https://github.com/plone/plone.formwidget.captcha)
- [ploneconf.theme](https://github.com/plone/ploneconf.theme)
- [plone.app.deco](https://github.com/plone/plone.app.deco)
- [dev.plone.org](https://github.com/plone/dev.plone.org)
- [mockup-training](https://github.com/plone/mockup-training)
- [paragon.addons](https://github.com/plone/paragon.addons)
- [plone_manager](https://github.com/plone/plone_manager)
- [api_angular](https://github.com/plone/api_angular)
- [experimental.nodtml](https://github.com/plone/experimental.nodtml)
- [buildout.jenkins](https://github.com/plone/buildout.jenkins)
- [plone.mocktestcase](https://github.com/plone/plone.mocktestcase)
- [plone.pony](https://github.com/plone/plone.pony)
- [plone.server](https://github.com/plone/plone.server)
- [Products.MasterSelectWidget](https://github.com/plone/Products.MasterSelectWidget)
- [plone.directives.form](https://github.com/plone/plone.directives.form)
- [zeoserver.docker](https://github.com/plone/zeoserver.docker)
- [heroku-button-plone](https://github.com/plone/heroku-button-plone)
- [paragon.site](https://github.com/plone/paragon.site)
- [heroku-buildpack-plone](https://github.com/plone/heroku-buildpack-plone)
- [ploneconf2017.theme](https://github.com/plone/ploneconf2017.theme)

**Comment by davisagli** [comment]
@gforcada Yep, looks all right with me

**Comment by gforcada** [comment]
@davisagli thanks! archived them all 🧹 🗑️ 

A last short one and I would be happy about it for a while 😆 

- https://github.com/plone/aiteam-builder
- https://github.com/plone/documentation-roboshots
- https://github.com/plone/Products.i18ntestcase
- https://github.com/plone/sphinx-landings
- https://github.com/plone/WinPloneInstaller
- https://github.com/plone/Products.PasswordResetTool
- https://github.com/plone/docs_2.0
- https://github.com/plone/plone.directives.tiles
- https://github.com/plone/plone-react-example
- https://github.com/plone/ploneorg.releasesecurityinfo
- https://github.com/plone/plone.app.modernizr
- https://github.com/plone/Products.TinyMCE
- https://github.com/plone/ploneconf2018.theme
- https://github.com/plone/plone.app.jquerytools
- https://github.com/plone/ploneorg.addonlisting
- https://github.com/plone/conference
- https://github.com/plone/plone4.csrffixes

**Comment by davisagli** [comment]
@gforcada go for it

**Comment by mauritsvanrees** [comment]
I would have suggested opening an issue in `plone/meta` if someone wants to unarchive, but I am too late. :-D

Plone 5.2 is out of maintenance in October this year, and out of security support one year later.  One of those would be a good time to archive `Products.Archetypes` and friends.  I suppose this year would be fine: if we need a security release of such a product, we can always unarchive.
