### ISSUE TITLE
Configure pipforester on tox.ini

### ISSUE THREAD

**Issue by gforcada** [plone/meta#77]
I was testing how `pipforester` works and came up with the following configuration:

```
[testenv]
allowlist_externals =
    sh
    dot

[testenv:circular]
usedevelop = true
deps =
    pipdeptree
    git+https://github.com/collective/pipforester
    -c https://dist.plone.org/release/6.0-dev/constraints.txt
commands =
    sh -c 'pipdeptree -j >forest.json'
    pipforester -i forest.json -o forest.dot --cycles
    dot -Tsvg -o forest.svg forest.dot
    dot -Tpng -o forest.png forest.dot
```

That allowed me to open https://github.com/plone/Products.CMFPlone/issues/3764 ✨ 

We might want to add either as a standalone `tox` environment, or, maybe better, fold it on the existing `dependencies` one 👍🏾

**Comment by mauritsvanrees** [comment]
@jensens Could we have a release of `pipforester` please?

**Comment by jensens** [comment]
I have this on my todo-list for the Beethoven sprint. There is a branch I want to merge first and add more docs.
