### ISSUE TITLE
Do not install all dependencies when using z3.dependencychecker

### ISSUE THREAD

**Issue by mauritsvanrees** [plone/meta#84]
Currently the `dependencies` tox environment installs all dependencies.  For `pipdeptree` this may be needed, but not for `z3c.dependencychecker`.  So maybe we can move this to a separate tox env.

Problem: the egg-info directory needs to be up to date.  This works:

```
[testenv:dependencychecker]
description = check if the package defines all its dependencies
# not sure if this setting is needed:
# usedevelop = true
skip_install = true
deps =
    z3c.dependencychecker==2.11
commands =
    python setup.py egg_info
    dependencychecker
```

But this assumes there is a `setup.py`.  Currently this is still true for all core Plone package I think, but this is likely to change.  Is there an alternative?

**Comment by gforcada** [comment]
Is `build` the tool that `setuptools` relies to build the `egg-info` folder? 🤔 

Seems like it: https://pypi.org/project/build/

```shell
pip install build
python -m build
```

And you get:

```
sdist/PKG.whl
sdist/PKG.tar.gz
PKG.egg-info
```

It does it by creating isolated environments, and probably as, in Plone at least, we don't have much `setup_requires` it does not even need to download the `install_requires` either 🎉

**Comment by gforcada** [comment]
So, indeed, we can avoid installing all the package dependencies 🍀 

That would allow us to more easily run as a `pre-commit` hook, or a mandatory/optional workflow even. So we get warned if you add/remove dependencies 🎉
